# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Multipart-Moya' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multipart-Moya
  pod 'Moya', '~> 14.0'
end
