# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LookViewPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LookViewPractice
  pod 'SnapKit', '~> 5.0.0'

  target 'LookViewPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LookViewPracticeUITests' do
    # Pods for testing
  end

end
